/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCreateWorkspaceRouteImport } from './routes/_app.create-workspace'
import { Route as AppWorkspaceWorkspaceIdRouteImport } from './routes/_app.workspace.$workspaceId'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './routes/_app.workspace.$workspaceId.index'
import { Route as AppWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_app.workspace.$workspaceId.settings'
import { Route as AppWorkspaceWorkspaceIdRunsIndexRouteImport } from './routes/_app.workspace.$workspaceId.runs.index'
import { Route as AppWorkspaceWorkspaceIdProvidersIndexRouteImport } from './routes/_app.workspace.$workspaceId.providers.index'
import { Route as AppWorkspaceWorkspaceIdMcpsIndexRouteImport } from './routes/_app.workspace.$workspaceId.mcps.index'
import { Route as AppWorkspaceWorkspaceIdApiKeysIndexRouteImport } from './routes/_app.workspace.$workspaceId.api-keys.index'
import { Route as AppWorkspaceWorkspaceIdAgentsIndexRouteImport } from './routes/_app.workspace.$workspaceId.agents.index'
import { Route as AppWorkspaceWorkspaceIdRunsRunIdRouteImport } from './routes/_app.workspace.$workspaceId.runs.$runId'
import { Route as AppWorkspaceWorkspaceIdProvidersProviderIdRouteImport } from './routes/_app.workspace.$workspaceId.providers.$providerId'
import { Route as AppWorkspaceWorkspaceIdMcpsMcpIdRouteImport } from './routes/_app.workspace.$workspaceId.mcps.$mcpId'
import { Route as AppWorkspaceWorkspaceIdApiKeysNewRouteImport } from './routes/_app.workspace.$workspaceId.api-keys.new'
import { Route as AppWorkspaceWorkspaceIdAgentsAgentIdRouteImport } from './routes/_app.workspace.$workspaceId.agents.$agentId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateWorkspaceRoute = AppCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdSettingsRoute =
  AppWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdRunsIndexRoute =
  AppWorkspaceWorkspaceIdRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdProvidersIndexRoute =
  AppWorkspaceWorkspaceIdProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdMcpsIndexRoute =
  AppWorkspaceWorkspaceIdMcpsIndexRouteImport.update({
    id: '/mcps/',
    path: '/mcps/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdApiKeysIndexRoute =
  AppWorkspaceWorkspaceIdApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdAgentsIndexRoute =
  AppWorkspaceWorkspaceIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdRunsRunIdRoute =
  AppWorkspaceWorkspaceIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdProvidersProviderIdRoute =
  AppWorkspaceWorkspaceIdProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdMcpsMcpIdRoute =
  AppWorkspaceWorkspaceIdMcpsMcpIdRouteImport.update({
    id: '/mcps/$mcpId',
    path: '/mcps/$mcpId',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdApiKeysNewRoute =
  AppWorkspaceWorkspaceIdApiKeysNewRouteImport.update({
    id: '/api-keys/new',
    path: '/api-keys/new',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdAgentsAgentIdRoute =
  AppWorkspaceWorkspaceIdAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/create-workspace': typeof AppCreateWorkspaceRoute
  '/': typeof AppIndexRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/agents/$agentId': typeof AppWorkspaceWorkspaceIdAgentsAgentIdRoute
  '/workspace/$workspaceId/api-keys/new': typeof AppWorkspaceWorkspaceIdApiKeysNewRoute
  '/workspace/$workspaceId/mcps/$mcpId': typeof AppWorkspaceWorkspaceIdMcpsMcpIdRoute
  '/workspace/$workspaceId/providers/$providerId': typeof AppWorkspaceWorkspaceIdProvidersProviderIdRoute
  '/workspace/$workspaceId/runs/$runId': typeof AppWorkspaceWorkspaceIdRunsRunIdRoute
  '/workspace/$workspaceId/agents': typeof AppWorkspaceWorkspaceIdAgentsIndexRoute
  '/workspace/$workspaceId/api-keys': typeof AppWorkspaceWorkspaceIdApiKeysIndexRoute
  '/workspace/$workspaceId/mcps': typeof AppWorkspaceWorkspaceIdMcpsIndexRoute
  '/workspace/$workspaceId/providers': typeof AppWorkspaceWorkspaceIdProvidersIndexRoute
  '/workspace/$workspaceId/runs': typeof AppWorkspaceWorkspaceIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/create-workspace': typeof AppCreateWorkspaceRoute
  '/': typeof AppIndexRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/agents/$agentId': typeof AppWorkspaceWorkspaceIdAgentsAgentIdRoute
  '/workspace/$workspaceId/api-keys/new': typeof AppWorkspaceWorkspaceIdApiKeysNewRoute
  '/workspace/$workspaceId/mcps/$mcpId': typeof AppWorkspaceWorkspaceIdMcpsMcpIdRoute
  '/workspace/$workspaceId/providers/$providerId': typeof AppWorkspaceWorkspaceIdProvidersProviderIdRoute
  '/workspace/$workspaceId/runs/$runId': typeof AppWorkspaceWorkspaceIdRunsRunIdRoute
  '/workspace/$workspaceId/agents': typeof AppWorkspaceWorkspaceIdAgentsIndexRoute
  '/workspace/$workspaceId/api-keys': typeof AppWorkspaceWorkspaceIdApiKeysIndexRoute
  '/workspace/$workspaceId/mcps': typeof AppWorkspaceWorkspaceIdMcpsIndexRoute
  '/workspace/$workspaceId/providers': typeof AppWorkspaceWorkspaceIdProvidersIndexRoute
  '/workspace/$workspaceId/runs': typeof AppWorkspaceWorkspaceIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/create-workspace': typeof AppCreateWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/_app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/_app/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/_app/workspace/$workspaceId/agents/$agentId': typeof AppWorkspaceWorkspaceIdAgentsAgentIdRoute
  '/_app/workspace/$workspaceId/api-keys/new': typeof AppWorkspaceWorkspaceIdApiKeysNewRoute
  '/_app/workspace/$workspaceId/mcps/$mcpId': typeof AppWorkspaceWorkspaceIdMcpsMcpIdRoute
  '/_app/workspace/$workspaceId/providers/$providerId': typeof AppWorkspaceWorkspaceIdProvidersProviderIdRoute
  '/_app/workspace/$workspaceId/runs/$runId': typeof AppWorkspaceWorkspaceIdRunsRunIdRoute
  '/_app/workspace/$workspaceId/agents/': typeof AppWorkspaceWorkspaceIdAgentsIndexRoute
  '/_app/workspace/$workspaceId/api-keys/': typeof AppWorkspaceWorkspaceIdApiKeysIndexRoute
  '/_app/workspace/$workspaceId/mcps/': typeof AppWorkspaceWorkspaceIdMcpsIndexRoute
  '/_app/workspace/$workspaceId/providers/': typeof AppWorkspaceWorkspaceIdProvidersIndexRoute
  '/_app/workspace/$workspaceId/runs/': typeof AppWorkspaceWorkspaceIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/create-workspace'
    | '/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/agents/$agentId'
    | '/workspace/$workspaceId/api-keys/new'
    | '/workspace/$workspaceId/mcps/$mcpId'
    | '/workspace/$workspaceId/providers/$providerId'
    | '/workspace/$workspaceId/runs/$runId'
    | '/workspace/$workspaceId/agents'
    | '/workspace/$workspaceId/api-keys'
    | '/workspace/$workspaceId/mcps'
    | '/workspace/$workspaceId/providers'
    | '/workspace/$workspaceId/runs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/create-workspace'
    | '/'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/agents/$agentId'
    | '/workspace/$workspaceId/api-keys/new'
    | '/workspace/$workspaceId/mcps/$mcpId'
    | '/workspace/$workspaceId/providers/$providerId'
    | '/workspace/$workspaceId/runs/$runId'
    | '/workspace/$workspaceId/agents'
    | '/workspace/$workspaceId/api-keys'
    | '/workspace/$workspaceId/mcps'
    | '/workspace/$workspaceId/providers'
    | '/workspace/$workspaceId/runs'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/create-workspace'
    | '/_app/'
    | '/_app/workspace/$workspaceId'
    | '/_app/workspace/$workspaceId/settings'
    | '/_app/workspace/$workspaceId/'
    | '/_app/workspace/$workspaceId/agents/$agentId'
    | '/_app/workspace/$workspaceId/api-keys/new'
    | '/_app/workspace/$workspaceId/mcps/$mcpId'
    | '/_app/workspace/$workspaceId/providers/$providerId'
    | '/_app/workspace/$workspaceId/runs/$runId'
    | '/_app/workspace/$workspaceId/agents/'
    | '/_app/workspace/$workspaceId/api-keys/'
    | '/_app/workspace/$workspaceId/mcps/'
    | '/_app/workspace/$workspaceId/providers/'
    | '/_app/workspace/$workspaceId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-workspace': {
      id: '/_app/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof AppCreateWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId': {
      id: '/_app/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/settings': {
      id: '/_app/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/runs/': {
      id: '/_app/workspace/$workspaceId/runs/'
      path: '/runs'
      fullPath: '/workspace/$workspaceId/runs'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRunsIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/providers/': {
      id: '/_app/workspace/$workspaceId/providers/'
      path: '/providers'
      fullPath: '/workspace/$workspaceId/providers'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdProvidersIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/mcps/': {
      id: '/_app/workspace/$workspaceId/mcps/'
      path: '/mcps'
      fullPath: '/workspace/$workspaceId/mcps'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdMcpsIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/api-keys/': {
      id: '/_app/workspace/$workspaceId/api-keys/'
      path: '/api-keys'
      fullPath: '/workspace/$workspaceId/api-keys'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdApiKeysIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/agents/': {
      id: '/_app/workspace/$workspaceId/agents/'
      path: '/agents'
      fullPath: '/workspace/$workspaceId/agents'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdAgentsIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/runs/$runId': {
      id: '/_app/workspace/$workspaceId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/workspace/$workspaceId/runs/$runId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRunsRunIdRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/providers/$providerId': {
      id: '/_app/workspace/$workspaceId/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/workspace/$workspaceId/providers/$providerId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdProvidersProviderIdRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/mcps/$mcpId': {
      id: '/_app/workspace/$workspaceId/mcps/$mcpId'
      path: '/mcps/$mcpId'
      fullPath: '/workspace/$workspaceId/mcps/$mcpId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdMcpsMcpIdRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/api-keys/new': {
      id: '/_app/workspace/$workspaceId/api-keys/new'
      path: '/api-keys/new'
      fullPath: '/workspace/$workspaceId/api-keys/new'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdApiKeysNewRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/agents/$agentId': {
      id: '/_app/workspace/$workspaceId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/workspace/$workspaceId/agents/$agentId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdAgentsAgentIdRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
  }
}

interface AppWorkspaceWorkspaceIdRouteChildren {
  AppWorkspaceWorkspaceIdSettingsRoute: typeof AppWorkspaceWorkspaceIdSettingsRoute
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
  AppWorkspaceWorkspaceIdAgentsAgentIdRoute: typeof AppWorkspaceWorkspaceIdAgentsAgentIdRoute
  AppWorkspaceWorkspaceIdApiKeysNewRoute: typeof AppWorkspaceWorkspaceIdApiKeysNewRoute
  AppWorkspaceWorkspaceIdMcpsMcpIdRoute: typeof AppWorkspaceWorkspaceIdMcpsMcpIdRoute
  AppWorkspaceWorkspaceIdProvidersProviderIdRoute: typeof AppWorkspaceWorkspaceIdProvidersProviderIdRoute
  AppWorkspaceWorkspaceIdRunsRunIdRoute: typeof AppWorkspaceWorkspaceIdRunsRunIdRoute
  AppWorkspaceWorkspaceIdAgentsIndexRoute: typeof AppWorkspaceWorkspaceIdAgentsIndexRoute
  AppWorkspaceWorkspaceIdApiKeysIndexRoute: typeof AppWorkspaceWorkspaceIdApiKeysIndexRoute
  AppWorkspaceWorkspaceIdMcpsIndexRoute: typeof AppWorkspaceWorkspaceIdMcpsIndexRoute
  AppWorkspaceWorkspaceIdProvidersIndexRoute: typeof AppWorkspaceWorkspaceIdProvidersIndexRoute
  AppWorkspaceWorkspaceIdRunsIndexRoute: typeof AppWorkspaceWorkspaceIdRunsIndexRoute
}

const AppWorkspaceWorkspaceIdRouteChildren: AppWorkspaceWorkspaceIdRouteChildren =
  {
    AppWorkspaceWorkspaceIdSettingsRoute: AppWorkspaceWorkspaceIdSettingsRoute,
    AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
    AppWorkspaceWorkspaceIdAgentsAgentIdRoute:
      AppWorkspaceWorkspaceIdAgentsAgentIdRoute,
    AppWorkspaceWorkspaceIdApiKeysNewRoute:
      AppWorkspaceWorkspaceIdApiKeysNewRoute,
    AppWorkspaceWorkspaceIdMcpsMcpIdRoute:
      AppWorkspaceWorkspaceIdMcpsMcpIdRoute,
    AppWorkspaceWorkspaceIdProvidersProviderIdRoute:
      AppWorkspaceWorkspaceIdProvidersProviderIdRoute,
    AppWorkspaceWorkspaceIdRunsRunIdRoute:
      AppWorkspaceWorkspaceIdRunsRunIdRoute,
    AppWorkspaceWorkspaceIdAgentsIndexRoute:
      AppWorkspaceWorkspaceIdAgentsIndexRoute,
    AppWorkspaceWorkspaceIdApiKeysIndexRoute:
      AppWorkspaceWorkspaceIdApiKeysIndexRoute,
    AppWorkspaceWorkspaceIdMcpsIndexRoute:
      AppWorkspaceWorkspaceIdMcpsIndexRoute,
    AppWorkspaceWorkspaceIdProvidersIndexRoute:
      AppWorkspaceWorkspaceIdProvidersIndexRoute,
    AppWorkspaceWorkspaceIdRunsIndexRoute:
      AppWorkspaceWorkspaceIdRunsIndexRoute,
  }

const AppWorkspaceWorkspaceIdRouteWithChildren =
  AppWorkspaceWorkspaceIdRoute._addFileChildren(
    AppWorkspaceWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppCreateWorkspaceRoute: typeof AppCreateWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateWorkspaceRoute: AppCreateWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
