/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppCreateWorkspaceRouteImport } from './routes/_app.create-workspace'
import { Route as AppWorkspaceWorkspaceIdRouteImport } from './routes/_app.workspace.$workspaceId'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './routes/_app.workspace.$workspaceId.index'
import { Route as AppWorkspaceWorkspaceIdProvidersRouteImport } from './routes/_app.workspace.$workspaceId.providers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateWorkspaceRoute = AppCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdProvidersRoute =
  AppWorkspaceWorkspaceIdProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/create-workspace': typeof AppCreateWorkspaceRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/providers': typeof AppWorkspaceWorkspaceIdProvidersRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/create-workspace': typeof AppCreateWorkspaceRoute
  '/workspace/$workspaceId/providers': typeof AppWorkspaceWorkspaceIdProvidersRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/create-workspace': typeof AppCreateWorkspaceRoute
  '/_app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/_app/workspace/$workspaceId/providers': typeof AppWorkspaceWorkspaceIdProvidersRoute
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/create-workspace'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/providers'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/create-workspace'
    | '/workspace/$workspaceId/providers'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/create-workspace'
    | '/_app/workspace/$workspaceId'
    | '/_app/workspace/$workspaceId/providers'
    | '/_app/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/create-workspace': {
      id: '/_app/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof AppCreateWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId': {
      id: '/_app/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/providers': {
      id: '/_app/workspace/$workspaceId/providers'
      path: '/providers'
      fullPath: '/workspace/$workspaceId/providers'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdProvidersRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
  }
}

interface AppWorkspaceWorkspaceIdRouteChildren {
  AppWorkspaceWorkspaceIdProvidersRoute: typeof AppWorkspaceWorkspaceIdProvidersRoute
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
}

const AppWorkspaceWorkspaceIdRouteChildren: AppWorkspaceWorkspaceIdRouteChildren =
  {
    AppWorkspaceWorkspaceIdProvidersRoute:
      AppWorkspaceWorkspaceIdProvidersRoute,
    AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
  }

const AppWorkspaceWorkspaceIdRouteWithChildren =
  AppWorkspaceWorkspaceIdRoute._addFileChildren(
    AppWorkspaceWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppCreateWorkspaceRoute: typeof AppCreateWorkspaceRoute
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateWorkspaceRoute: AppCreateWorkspaceRoute,
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
